name: create daily docker image on develop
on:
  push:
    branches:
      - stp-changes
  pull_request:
    branches: [stp-changes]
  workflow_dispatch:
  schedule:
   - cron: "0 2 * * *"
jobs:
  publish-docker-develop-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: stp-changes
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build the openimis backend Docker image
      run: |
         LABEL=latest
         docker build . --tag ghcr.io/stssocialst-stp/kenon-backend:${LABEL}
         docker push ghcr.io/stssocialst-stp/kenon-backend:${LABEL}
